services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: edupath
      POSTGRES_USER: edupath
      POSTGRES_PASSWORD: edupath
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      # 5433 en el host para no chocar con un Postgres local en 5432
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U edupath -d edupath"]
      interval: 5s
      timeout: 5s
      retries: 10

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DJANGO_DEBUG: "true"
      DJANGO_SECRET_KEY: change-me-in-prod
      DJANGO_ALLOWED_HOSTS: "*"
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_DB: edupath
      POSTGRES_USER: edupath
      POSTGRES_PASSWORD: edupath
      CORS_ALLOWED_ORIGINS: http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174
      CSRF_TRUSTED_ORIGINS: http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174
      LEGACY_SYNC_API_KEY: legacy-dev-key
      CERT_SIGNING_SECRET: cert-hmac-dev-secret
      PASSWORD_RESET_FRONTEND_URL: http://localhost:5174/recuperar-cuenta
      GUNICORN_WORKERS: "3"
      EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
      EMAIL_HOST: mailhog
      EMAIL_PORT: "1025"
      EMAIL_USE_TLS: "false"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # Obliga al backend a esperar el OK del healthcheck
      mailhog:
        condition: service_started

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5174:80"
    depends_on:
      - backend

volumes:
  pgdata: