# Generated by Django 5.2.16 on 2026-07-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('no_iniciada', 'No iniciada'), ('en_progreso', 'En progreso'), ('completada', 'Completada')], default='no_iniciada', max_length=20)),
                ('porcentaje', models.PositiveIntegerField(default=0)),
                ('tiempo_segundos', models.PositiveIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Progreso de lección',
                'verbose_name_plural': 'Progresos de lección',
            },
        ),
    ]
