# Generated by Django 5.2.16 on 2026-07-16 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0002_initial'),
        ('progreso', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progresoleccion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progresoleccion',
            name='leccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='cursos.leccion'),
        ),
        migrations.AlterUniqueTogether(
            name='progresoleccion',
            unique_together={('estudiante', 'leccion')},
        ),
    ]
