# Generated by Django 5.2.16 on 2026-07-16 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField(default=dict)),
                ('canvas_payload', models.JSONField(blank=True, default=dict)),
                ('puntaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('aprobado', models.BooleanField(default=False)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Intento',
                'verbose_name_plural': 'Intentos',
                'ordering': ['-iniciado_en'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('opcion_multiple', 'Opción múltiple'), ('verdadero_falso', 'Verdadero/Falso'), ('canvas_hotspot', 'Hotspot Canvas'), ('canvas_dibujo', 'Dibujo Canvas')], max_length=30)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('puntaje', models.PositiveIntegerField(default=1)),
                ('opciones', models.JSONField(blank=True, default=list)),
                ('respuesta_correcta', models.JSONField(default=dict)),
                ('canvas_config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tiempo_limite_seg', models.PositiveIntegerField(default=600)),
                ('puntaje_aprobacion', models.PositiveIntegerField(default=70)),
                ('canvas_schema', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=True)),
                ('leccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='cursos.leccion')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
    ]
