# Generated by Django 5.2.16 on 2026-07-21 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('acceso_contenido', 'Acceso a contenido'), ('emision_certificado', 'Emisión de certificado')], max_length=40)),
                ('objeto_tipo', models.CharField(blank=True, max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=50)),
                ('ruta', models.CharField(blank=True, max_length=255)),
                ('metodo', models.CharField(blank=True, max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['accion', '-creado_en'], name='administrac_accion_6bfd85_idx'), models.Index(fields=['usuario', '-creado_en'], name='administrac_usuario_d7b60a_idx')],
            },
        ),
    ]
