# Generated by Django 5.2.16 on 2026-07-16 01:21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('emitido_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('firma_hmac', models.CharField(editable=False, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('revocado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-emitido_en'],
            },
        ),
    ]
