# Generated by Django 5.2.16 on 2026-07-16 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificados', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='cursos.curso'),
        ),
    ]
